package ravn_gpu

MAX_PIPELINE_BIND_CONSTANTS     :: 8
MAX_PIPELINE_BIND_SAMPLERS      :: 8
MAX_PIPELINE_BIND_RESOURCES     :: 32
MAX_PIPELINE_BIND_RW_RESOURCES  :: 32

MAX_BIND_GROUP_CONSTANTS     :: MAX_PIPELINE_BIND_CONSTANTS / MAX_PIPELINE_BIND_GROUPS
MAX_BIND_GROUP_SAMPLERS      :: MAX_PIPELINE_BIND_SAMPLERS / MAX_PIPELINE_BIND_GROUPS
MAX_BIND_GROUP_RESOURCES     :: MAX_PIPELINE_BIND_RESOURCES / MAX_PIPELINE_BIND_GROUPS
MAX_BIND_GROUP_RW_RESOURCES  :: MAX_PIPELINE_BIND_RW_RESOURCES / MAX_PIPELINE_BIND_GROUPS

MAX_PIPELINE_BIND_GROUPS :: 2
MAX_PIPELINE_VERTEX_LAYOUTS :: 4

NUM_TOTAL_BIND_GROUP_SLOTS ::
    MAX_BIND_GROUP_CONSTANTS +
    MAX_BIND_GROUP_SAMPLERS +
    MAX_BIND_GROUP_RESOURCES +
    MAX_BIND_GROUP_RW_RESOURCES

BIND_GROUP_CONSTANTS_SLOT_SHIFT :: 0
BIND_GROUP_SAMPLER_SLOT_SHIFT :: BIND_GROUP_CONSTANTS_SLOT_SHIFT + MAX_BIND_GROUP_SAMPLERS
BIND_GROUP_RESOURCE_SLOT_SHIFT :: BIND_GROUP_CONSTANTS_SLOT_SHIFT + MAX_BIND_GROUP_RESOURCES
BIND_GROUP_RW_RESOURCE_SLOT_SHIFT :: BIND_GROUP_RESOURCE_SLOT_SHIFT + MAX_BIND_GROUP_RW_RESOURCES
